{% set version = "1.5.4" %}

package:
  name: crisprme
  version: {{ version }}

source:
  url: https://github.com/samuelecancellieri/CRISPRme/archive/v{{ version }}.tar.gz
  sha256: 1de4287b57a8ca4fa3984488c10922af8089fa6eb3b5cf0598344ee88e7c2169
  
build:
  number: 0
  noarch: generic
  
requirements:
  run:
    - zip
    - crispritz
    - dash=1.10.0
    - dash-bootstrap-components=0.10.0
    - dash-core-components=1.9.0
    - dash-daq=0.4.0
    - dash-html-components=1.0.3
    - dash-renderer=1.3.0
    - dash-table=4.6.2
    - flask=1.1.2
    - flask-caching=1.7.1
    - flask-compress=1.5.0
    - fontconfig=2.13.1
    - freetype=2.10.1
    - future=0.18.2
    - gettext=0.19.8.1
    - gunicorn=20.0.4

test:
  commands:
    - crisprme.py

about:
  home: https://github.com/samuelecancellieri/CRISPRme
  license: GPL3
  license_file: LICENSE
  summary: CRISPRme, tool package for CRISPR experiments assessment and analysis.
