{% set name="womtool" %}
{% set version="59" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/broadinstitute/cromwell/archive/{{ version }}.tar.gz
  sha256: 03f52e4f624082eaab704eab1db2d85aa63a9c781152007234c265154d6427a1

build:
  noarch: generic
  number: 0

requirements:
  host:
    - openjdk=8
    - sbt
    - scala
  run:
    - openjdk=8
    - python

test:
  commands:
    - womtool --help

about:
  home: https://cromwell.readthedocs.io/en/develop/WOMtool/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "Command line utilities for interacting with WDL"

extra:
  identifiers:
    - biotools:womtool
