{% set version = "0.5.1" %}
{% set sha256 = "276fff9e536ddab4af19217efc82e414d832ff74540ac1925805538d65c2d096" %}

package:
  name: binsanity
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/b/binsanity/Binsanity-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 0
  script: $PYTHON -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - biopython
    - pandas >=0.13.0
    - scipy >=0.13.0
    - checkm-genome
    - scikit-learn >=0.23
    - subread

test:
  commands:
    - Binsanity -h

about:
  home: https://github.com/edgraham/BinSanity
  license: GPL-3.0
  license_family: GPL
  summary: Method to cluster contigs based a biphasic method with coverage and composition
