{% set mothurVersion = "1.45.0" %}
{% set mothurSha256 = "b22e1b4ba8686f4e77e6a55a30a1a1cb6490b651398b0756d84f80314f55aa70" %}
{% set vsearchVersion = "2.13.3" %}

package:
  name: mothur
  version: {{ mothurVersion }}

source:
  url: https://github.com/mothur/mothur/archive/v.{{ mothurVersion }}.tar.gz
  sha256: {{ mothurSha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - blast-legacy
    - boost-cpp
    - gsl
    - hdf5
    - readline
    - sra-tools
    - vsearch ={{ vsearchVersion }}
    - zlib
  run:
    - blast-legacy
    - boost-cpp
    - gsl
    - hdf5
    - readline
    - sra-tools
    - vsearch ={{ vsearchVersion }}
    - zlib

test:
  commands:
    - mothur "#help()"
    - uchime --version

about:
  home: http://www.mothur.org
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.md
  summary: This project seeks to develop a single piece of open-source, expandable software to fill the bioinformatics needs of the microbial ecology community.
  dev_url: https://github.com/mothur/mothur

extra:
  identifiers:
    - doi:10.1128/AEM.01541-09
    - usegalaxy-eu:mothur_get_label
